### ISSUE TITLE
xml export with links for institutions broken

### ISSUE THREAD

**Issue by PietroLiuzzo** [BetaMasaheft/Documentation#1033]
and the web XML file (how is it called?) of all (?) place records results in an error, for example http://betamasaheft.eu/tei/LOC1022Abbay.xml

> HTTP ERROR 500
> Problem accessing /exist/apps/BetMas/tei/LOC1022Abbay.xml. Reason:
> 
>     Server Error
> Caused by:
> javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/tei/LOC1022Abbay.xml: An error occurred: SAX exception while transforming node: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 121; The prefix "xml" cannot be bound to any namespace other than its usual namespace; neither can the namespace for "xml" be bound to any prefix other than "xml".
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:531)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by PietroLiuzzo** [comment]
duplicate
