### ISSUE TITLE
server error 

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#1353]
I get this error for LIT2000Mazmur, LIT2362Songof, LIT2509Weddas and LIT1113Anqasa
I don't see any obvious problems in the records
```
HTTP ERROR 500
Problem accessing /exist/apps/BetMas/works/LIT2509Weddas/main. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/works/LIT2509Weddas/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: substring-before($source as xs:string?, $search as xs:string?) xs:string?. Expected cardinality: zero or one, got 2. [at line 970, column 59, source: /db/apps/BetMas/modules/item.xqm]
In function:
	item2:RestMss(item()*) [1166:59:/db/apps/BetMas/modules/item.xqm]
	item2:RestSeeAlso(item()*, item()*) [1238:6:/db/apps/BetMas/modules/item.xqm]
	item2:RestItem(item()*, item()*) [503:36:/db/apps/BetMas/modules/item.xqm]
	restItem:ITEM(item()*, item()*, item()*, xs:integer*, xs:integer*, xs:string*) [73:1:/db/apps/BetMas/modules/items.xqm]
	restItem:getItemC(xs:string*, xs:string*, xs:integer*, xs:integer*, xs:string*) [-1:-1:/db/apps/BetMas/modules/items.xqm]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by PietroLiuzzo** [comment]
Can you by chance spare me the hunt ? do you remember any BNF manuscript which has more than an msIdentifier with idno/@facs? just in case you have it on top of your head already, I will look for it otherwise. the code needs to be fixed anyway

**Comment by thea-m** [comment]
More than one idno/@facs? No, sorry... Many of them have more than one idno, but always (?) only one @facs

**Comment by PietroLiuzzo** [comment]
thanks, just in case...

**Comment by PietroLiuzzo** [comment]
should be fine now

**Comment by thea-m** [comment]
yes, thank you!
