### ISSUE TITLE
manuscripts with the same content function assumes only one locus in msItem

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#880]
there seems to be a problem with http://betamasaheft.eu/works/LIT1882MarkGo/main:
HTTP ERROR 500
Problem accessing /exist/apps/BetMas/works/LIT1882MarkGo/main. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/works/LIT1882MarkGo/main: exerr:ERROR XPTY0004: The actual cardinality for parameter string:tei2string($h/preceding-sibling::t:locus) does not match the cardinality declared in the function's signature: zero or one. Expected cardinality: string:tei2string($h/preceding-sibling::t:locus), got zero or one. [at line 777, column 125, source: /db/apps/BetMas/modules/item.xqm]
In function:
	item:RestMss(item()*) [877:31:/db/apps/BetMas/modules/item.xqm]
	item:RestSeeAlso(item()*, item()*) [928:6:/db/apps/BetMas/modules/item.xqm]
	item:RestItem(item()*, item()*) [359:4:/db/apps/BetMas/modules/item.xqm]
	restItem:ITEM(item()*, item()*, item()*, xs:integer*, xs:integer*, xs:string*) [71:1:/db/apps/BetMas/modules/items.xql]
	restItem:getItem(xs:string*, xs:string*, xs:integer*, xs:integer*, xs:string*) [-1:-1:/db/apps/BetMas/modules/items.xql]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:716)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	at java.lang.Thread.run(Thread.java:748)

**Comment by PietroLiuzzo** [comment]
from a first inquire into this issue the problem seams to manyfolded.
- things encoded like IVefiopsk17 and 18 where `<locus target="28v"/>` is to be found as placement for this work record instead of the encoding-wise correct `<locus target="#28v"/>` do not help
- the code is currently and wrongly assuming that there is only one `locus` before `title` in a msItem, which is not true, e.g. for this example in BDLaethc1. I have fixed this but you are likely to have to wait a release or a reboot with the latest version of the code at least to see this changed.
