### ISSUE TITLE
links in catalogue view broken

### ISSUE THREAD

**Issue by thea-m** [BetaMasaheft/Documentation#936]
the links don't work here:
http://betamasaheft.eu/catalogues/list
HTTP ERROR 500
Problem accessing /exist/apps/BetMas/catalogues/GrebTiss1935Codices/list. Reason:

    Server Error
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/catalogues/GrebTiss1935Codices/list: exerr:ERROR Error while evaluating expression: collection('/db/apps/BetMas/data/manuscripts')//t:TEI[descendant::t:listBibl[@type='catalogue'][descendant::t:ptr[@target='bm:GrebTiss1935Codices']]][]. org.exist.xquery.XPathException: err:XPST0003 unexpected token: ] [at line 1, column 151]
 [at line 946, column 27]
In function:
	apprest:listrest(item()*, item()*, map(*), item()*) [1007:16:/db/apps/BetMas/modules/apprest.xqm]
	list:getcataloguelist(xs:string*, xs:integer*, xs:integer*, xs:integer*, xs:integer*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMas/modules/list.xql]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/catalogues/GrebTiss1935Codices/list: exerr:ERROR Error while evaluating expression: collection('/db/apps/BetMas/data/manuscripts')//t:TEI[descendant::t:listBibl[@type='catalogue'][descendant::t:ptr[@target='bm:GrebTiss1935Codices']]][]. org.exist.xquery.XPathException: err:XPST0003 unexpected token: ] [at line 1, column 151]
 [at line 946, column 27]

**Comment by thea-m** [comment]
thank you!
